# configure mysql db

---
- name: creating shrine database user
  shell: mysql -u root --execute "CREATE USER 'shrine'@'localhost' IDENTIFIED BY 'demouser';"

- name: updating full privilages for shrine user in mysql
  command: mysql -u root --execute="GRANT ALL privileges ON *.* TO 'shrine'@'localhost';"

- name: flush privs  
  command: mysql -u root --execute="FLUSH PRIVILEGES;"