# creating mysql databases

---
- name: creating mysql databases
  shell: mysql --user=shrine --password=demouser --execute "CREATE DATABASE adapterAuditDB;"
  shell: mysql --user=shrine --password=demouser --execute "CREATE DATABASE qepAuditDB;"
  shell: mysql --user=shrine --password=demouser --execute "CREATE DATABASE stewardDB;"
  shell: mysql --user=shrine --password=demouser --execute "CREATE DATABASE shrine_query_history;"