# configure mysql db

---
- name: downloading shrine-setup to tmp directory
  shell: "wget -O /tmp/shrine-setup.zip https://repo.open.catalyst.harvard.edu/nexus/content/groups/public/net/shrine/shrine-setup/3.1.0/shrine-setup-3.1.0-dist.zip"
 
- name: installing unzip
  shell: "sudo yum install zip unzip -y"

- name: unzip shrine-setup.zip
  shell: "unzip /tmp/shrine-setup.zip"

#- name: creating shrine database user
#  shell: mysql -u root --execute "CREATE USER 'shrine'@'localhost' IDENTIFIED BY 'demouser';"

- name: creating mysql databases
  shell: mysql --user=shrine --password=demouser --execute "CREATE DATABASE adapterAuditDB;"
  shell: mysql --user=shrine --password=demouser --execute "CREATE DATABASE qepAuditDB;"
  shell: mysql --user=shrine --password=demouser --execute "CREATE DATABASE stewardDB;"
  shell: mysql --user=shrine --password=demouser --execute "CREATE DATABASE shrine_query_history;"

        