# tasks file for roles/shrine_install

---

- include: system services:update.yml

- include: JDK_11_Install_Playbook.yml

- include: tomcat configuration.yml

- include: environment variables tomcat_java.yml

<<<<<<< HEAD
- include: install-mysql-db.yml

- include: configure_mysql_db.yml
=======
- include: download_shrine-setup.yml

- include: install-mysql-db.yml

- include: create_shrine_db_user.yml

- include: creating_mysql_db_databases.yml

- include: install_mysql_schemas.yml
>>>>>>> Update-001

- include: configuring_database_connections.yml

- include: installing_shrine.yml

- include: shrine_conf_setup.yml

- include: installing_lucene_indicies.yml

<<<<<<< HEAD
- include: install_keystore_adaptMapp.yml
=======
- include: adapter_mappings.yml

- include: shrine_keystore.yml
>>>>>>> Update-001
