# installing shrine keystore

---
- name: change directory
  shell: "cd /opt/shrine"

- name: download shrine keystore
  shell: "wget https://shrine-dev-files-001.s3.amazonaws.com/shrine.keystore -O /opt/shrine/shrine.keystore"

- name: start shrine service
  shell: "sudo service shrine start"